import { motion } from 'motion/react';
import { Flame, Github } from 'lucide-react';

export interface RoastData {
  username: string;
  avatar: string;
  score: number;
  category: string;
  roasts: string[];
}

interface RoastCardProps {
  data: RoastData;
}

export function RoastCard({ data }: RoastCardProps) {
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9, y: 20 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-2xl mx-auto"
      id="roast-card"
    >
      <div className="relative bg-gradient-to-br from-purple-900/60 to-blue-900/60 backdrop-blur-lg rounded-3xl p-8 md:p-12 border border-white/30 shadow-2xl overflow-hidden">
        {/* Background pattern */}
        <div className="absolute inset-0 opacity-5">
          <div className="absolute inset-0" style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
          }} />
        </div>

        {/* Glow effect */}
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-500/30 rounded-full blur-3xl" />
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-500/30 rounded-full blur-3xl" />

        {/* Content */}
        <div className="relative z-10">
          {/* Header */}
          <div className="flex flex-col md:flex-row items-center md:items-start gap-6 mb-8">
            <motion.img
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.2, type: 'spring', stiffness: 200 }}
              src={data.avatar}
              alt={data.username}
              className="w-24 h-24 md:w-28 md:h-28 rounded-full border-4 border-white/40 shadow-lg"
            />
            <div className="flex-1 text-center md:text-left">
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">
                @{data.username}
              </h3>
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 }}
                className="inline-flex items-center gap-2 bg-gradient-to-r from-orange-500 to-red-500 px-4 py-2 rounded-full shadow-lg"
              >
                <Flame size={20} className="text-white" />
                <span className="text-white font-bold text-lg">
                  Roast Score: {data.score}/100
                </span>
              </motion.div>
            </div>
          </div>

          {/* Roast points */}
          <div className="space-y-4 mb-8">
            {data.roasts.map((roast, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.4 + index * 0.1 }}
                className="flex items-start gap-4 bg-black/20 backdrop-blur-sm rounded-2xl p-4 border border-white/10"
              >
                <div className="flex-shrink-0 mt-1">
                  <Flame size={20} className="text-orange-400" />
                </div>
                <p className="text-gray-200 text-base md:text-lg leading-relaxed">
                  {roast}
                </p>
              </motion.div>
            ))}
          </div>

          {/* Category badge */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.8 }}
            className="flex items-center justify-between flex-wrap gap-4"
          >
            <div className="bg-white/10 backdrop-blur-sm px-6 py-3 rounded-full border border-white/20">
              <span className="text-gray-300 font-medium">
                Category: <span className="text-white font-bold">{data.category}</span>
              </span>
            </div>

            {/* Footer branding */}
            <div className="flex items-center gap-2 text-gray-400 text-sm">
              <Github size={16} />
              <span>Generated by GitHub Roast Tool</span>
            </div>
          </motion.div>
        </div>
      </div>
    </motion.div>
  );
}
